### ISSUE TITLE
Modding Toolkit for Batman: Arkham Asylum, City, Origins, Origins Online, and Knight

### ISSUE THREAD

**Issue by Wastelander121** [Wastelander121/ArkhamExplorer#1]
We need someone to create an editing software for the Arkham Games.

This toolset needs to be able to do the following:
Be compatible with Arkham Asylum, City, Origins, Online and Knight
Have a user-friendly interface and clear tooltips for each feature.
Allow for 3D model swapping and importing
Be able to create and edit maps
Be able to import and replace animations
Be able to edit scripts 
Reindex UPKs, giving us the ability to add new entries to UPK files instead of just replacing files.

Note: Please make sure that the modding toolkit is legal and does not violate any copyright laws and is appropriately licensed.

**Comment by england2** [comment]
do it yourself homeboy

**Comment by FCH823** [comment]
Done!
Well... maybe not the stuff about maps, anims, scripts, clear tooltips...reindex UPKs ?
